import streamlit as st
import psycopg2
import json
import pandas as pd

# 1. Page Configuration
st.set_page_config(page_title="IPO AI Analyst", page_icon="📈", layout="wide")
st.title("📈 AI-Powered IPO Analytics")
st.markdown("Live insights generated by Google Gemini & Supabase")

# 2. Database Connection
@st.cache_resource
def init_connection():
    # Streamlit uses a special secrets manager
    return psycopg2.connect(st.secrets["DATABASE_URL"])

try:
    conn = init_connection()
except Exception as e:
    st.error(f"Could not connect to database: {e}")
    st.stop()

# 3. Fetch Data
@st.cache_data(ttl=600) # Caches the data for 10 minutes to save database queries
def get_ipo_data():
    query = """
        SELECT m.symbol, m.company_name, a.listing_score, a.overall_rating, a.ai_insights, a.market_data
        FROM ipo_master m
        JOIN ipo_assessments a ON m.ipo_id = a.ipo_id
        ORDER BY a.created_at DESC;
    """
    return pd.read_sql(query, conn)

df = get_ipo_data()

# 4. Build the UI
if df.empty:
    st.warning("No IPO data found in the database yet!")
else:
    # Sidebar for selection
    st.sidebar.header("Select an IPO")
    selected_symbol = st.sidebar.selectbox("Active IPOs", df['symbol'].tolist())
    
    # Filter data for the selected IPO
    ipo_data = df[df['symbol'] == selected_symbol].iloc[0]
    insights = ipo_data['ai_insights']
    if isinstance(insights, str):
        insights = json.loads(insights)
        
    market_data = ipo_data['market_data']
    if isinstance(market_data, str):
        market_data = json.loads(market_data)

    # Top Metrics Row
    col1, col2, col3 = st.columns(3)
    col1.metric("Listing Score", f"{ipo_data['listing_score']}/100")
    col2.metric("Overall Rating", ipo_data['overall_rating'])
    col3.metric("Live GMP", f"₹{market_data.get('current_gmp', 0)}")

    st.divider()

    # AI Insights Section
    st.subheader("🤖 AI Executive Summary")
    st.write(insights.get("executive_summary", "No summary available."))

    col_bull, col_bear = st.columns(2)
    with col_bull:
        st.success("🐂 Bull Case")
        st.write(insights.get("bull_case", "N/A"))
        st.write("**Key Positives:**")
        for pos in insights.get("key_positives", []):
            st.markdown(f"- {pos}")

    with col_bear:
        st.error("🐻 Bear Case")
        st.write(insights.get("bear_case", "N/A"))
        st.write("**Red Flags:**")
        for flag in insights.get("red_flags", []):
            st.markdown(f"- {flag}")
